"""
Property Bureau Member Data Submission Standard V1.1 — canonical optimized spec.
Derived from V1.0 + Critical Evaluation Report (June 2026).
"""

VERSION = "V1.1"
PREVIOUS_VERSION = "V1.0"

# Field tuple: category, name, description, dtype, length, mandatory, validation, enum, sample, matching, remarks, source, derived_by_bureau
FIELDS_V11 = [
    ("SUBMISSION_HEADER", "SUBMISSION_REFERENCE", "Unique batch reference from member.", "STRING", "50", "Y",
     "Alphanumeric, hyphen, underscore; unique per MEMBER_INSTITUTION_CODE / 24 months.", "", "ABC-HFC-PROP-2026-Q1-001", "",
     "", "02_field_specification.csv", "N"),
    ("SUBMISSION_HEADER", "MEMBER_INSTITUTION_CODE", "Bureau-issued institution code.", "STRING", "20", "Y",
     "Uppercase alphanumeric; must exist in bureau master.", "", "HFC0000042", "", "",
     "02_field_specification.csv", "N"),
    ("SUBMISSION_HEADER", "REPORTING_PERIOD_END", "Portfolio as-of date.", "DATE", "10", "Y",
     "ISO 8601 YYYY-MM-DD.", "", "2026-03-31", "", "Authoritative snapshot date.",
     "02_field_specification.csv", "N"),
    ("SUBMISSION_HEADER", "SUBMISSION_TYPE", "FULL, DELTA, or REFRESH.", "ENUM", "20", "Y",
     "SUBMISSION_TYPE enum.", "SUBMISSION_TYPE", "FULL", "", "",
     "03_enum_master.csv", "N"),
    ("SUBMISSION_HEADER", "CONTACT_EMAIL", "Operations contact for exceptions.", "STRING", "120", "Y",
     "RFC 5322 simplified email.", "", "dataops@abchfc.example.in", "", "",
     "02_field_specification.csv", "N"),
    ("SUBMISSION_HEADER", "TOTAL_RECORD_COUNT", "Property row count in batch (optional).", "INTEGER", "10", "N",
     "If supplied, bureau compares to received count (INFO on mismatch).", "", "75", "", "Demoted per FB-017.",
     "Critical Evaluation §5 VR-002", "N"),

    ("SUBMISSION_CONTROL", "RECORD_TYPE", "Legacy sparse combined-file discriminator — omit in Option B dense file.", "ENUM", "20", "L",
     "Not used in primary dense single-file submission.", "RECORD_TYPE", "", "",
     "Deprecated; use dense PROPERTY_BUREAU_SUBMISSION.csv.", "V1.1 Option B primary", "N"),

    ("INSTITUTION_REFERENCE", "MEMBER_LOAN_ACCOUNT_NUMBER", "Member loan account number.", "STRING", "40", "Y",
     "Unique ACTIVE per institution per period.", "", "ABC-HL-0001", "", "",
     "02_field_specification.csv", "N"),
    ("INSTITUTION_REFERENCE", "MEMBER_PROPERTY_REFERENCE", "Stable member collateral reference.", "STRING", "40", "Y",
     "Immutable for same physical collateral.", "", "ABC-COL-0001", "HIGH", "",
     "02_field_specification.csv", "N"),
    ("INSTITUTION_REFERENCE", "MEMBER_CUSTOMER_ID", "CIF / customer id.", "STRING", "40", "C",
     "Required when BORROWER_TYPE not INDIVIDUAL; optional for individuals.", "", "ABC-CIF-100001", "", "",
     "Critical Evaluation §5 cross-section", "N"),

    ("PROPERTY_CORE", "PROPERTY_TYPE", "Collateral type.", "ENUM", "20", "Y", "PROPERTY_TYPE enum.", "PROPERTY_TYPE", "RESIDENTIAL", "HIGH", "",
     "02_field_specification.csv", "N"),
    ("PROPERTY_CORE", "PROPERTY_SUBTYPE", "Collateral subtype.", "ENUM", "30", "Y", "Valid per PROPERTY_TYPE crosswalk.", "PROPERTY_SUBTYPE", "APARTMENT", "HIGH", "",
     "03b_enum_property_subtype_crosswalk.csv", "N"),
    ("PROPERTY_CORE", "CONSTRUCTION_STATUS", "Built status.", "ENUM", "20", "Y", "CONSTRUCTION_STATUS enum.", "CONSTRUCTION_STATUS", "COMPLETED", "MEDIUM", "",
     "02_field_specification.csv", "N"),
    ("PROPERTY_CORE", "OCCUPANCY_STATUS", "Occupancy (completed properties).", "ENUM", "20", "C",
     "Required when CONSTRUCTION_STATUS=COMPLETED; N/A if under construction.", "OCCUPANCY_STATUS", "SELF_OCCUPIED", "LOW",
     "UNDER_CONSTRUCTION removed from enum per FB-024.", "Critical Evaluation §6.3", "N"),

    ("PROPERTY_LOCATION", "ADDRESS_LINE_1", "Primary property address.", "STRING", "200", "Y",
     "Min 10 characters.", "", "42 Ring Road Sector 9", "CRITICAL", "",
     "02_field_specification.csv", "N"),
    ("PROPERTY_LOCATION", "LOCALITY", "Area / neighbourhood.", "STRING", "120", "Y", "Min 3 characters.", "", "Vashi", "CRITICAL", "",
     "02_field_specification.csv", "N"),
    ("PROPERTY_LOCATION", "CITY", "City or town.", "STRING", "80", "Y", "", "", "Navi Mumbai", "CRITICAL", "",
     "02_field_specification.csv", "N"),
    ("PROPERTY_LOCATION", "DISTRICT", "District.", "STRING", "80", "N",
     "Bureau may derive from PINCODE master when blank.", "", "Thane", "HIGH", "Optional per FB-030 PIN simplification.",
     "Critical Evaluation §7.2", "Y"),
    ("PROPERTY_LOCATION", "STATE", "State / UT code.", "ENUM", "3", "Y", "INDIAN_STATE_UT enum.", "INDIAN_STATE_UT", "MH", "CRITICAL", "",
     "03_enum_master.csv", "N"),
    ("PROPERTY_LOCATION", "PINCODE", "6-digit PIN.", "STRING", "6", "Y", "Regex ^[1-9][0-9]{5}$; bureau PIN master validation.", "", "400703", "CRITICAL", "",
     "04_validation_rules.csv VR-007", "N"),

    ("PROPERTY_IDENTIFIERS", "FLAT_NUMBER", "Unit / flat number.", "STRING", "30", "C",
     "Required for APARTMENT, OFFICE, SHOP.", "", "1204", "CRITICAL", "",
     "VR-015", "N"),
    ("PROPERTY_IDENTIFIERS", "PLOT_NUMBER", "Plot number.", "STRING", "40", "C",
     "Required for PLOT, LAND, VILLA, ROW_HOUSE, etc.", "", "Plot 42", "CRITICAL", "",
     "02_field_specification.csv", "N"),
    ("PROPERTY_IDENTIFIERS", "SURVEY_NUMBER", "Survey / khasra.", "STRING", "60", "C",
     "Required for AGRICULTURAL or rural PLOT/LAND.", "", "124/2A", "CRITICAL", "",
     "VR-014", "N"),
    ("PROPERTY_IDENTIFIERS", "CTS_NUMBER", "City survey number.", "STRING", "60", "N", "", "", "CTS 456/B/2", "CRITICAL", "Optional not conditional-mandatory.",
     "Critical Evaluation §8.1", "N"),
    ("PROPERTY_IDENTIFIERS", "PROJECT_NAME", "RERA / project name.", "STRING", "200", "C",
     "Required for APARTMENT, VILLA, ROW_HOUSE urban.", "", "Prestige Lakeside Habitat", "CRITICAL", "",
     "02_field_specification.csv", "N"),
    ("PROPERTY_IDENTIFIERS", "BUILDING_UNIT_IDENTIFIER", "Building, tower, wing (combined).", "STRING", "180", "C",
     "Replaces BUILDING_NAME + TOWER_NAME per FB-009.", "", "Tower B Block 4", "CRITICAL", "",
     "Critical Evaluation §4", "N"),
    ("PROPERTY_IDENTIFIERS", "MUNICIPAL_AUTHORITY_ID", "Khata / PID / PTIN value.", "STRING", "60", "N",
     "Pair with MUNICIPAL_ID_TYPE.", "", "KH-908712", "CRITICAL", "Consolidates 3 fields per FB-012.",
     "Critical Evaluation §4", "N"),
    ("PROPERTY_IDENTIFIERS", "MUNICIPAL_ID_TYPE", "Type of municipal id.", "ENUM", "10", "C",
     "Required when MUNICIPAL_AUTHORITY_ID populated.", "MUNICIPAL_ID_TYPE", "KHATA", "HIGH", "",
     "Critical Evaluation §6.3", "N"),

    ("PROPERTY_PHYSICAL", "BUILT_UP_AREA", "Built-up area.", "DECIMAL", "12,4", "N", "Positive.", "", "1450.5000", "MEDIUM", "",
     "02_field_specification.csv", "N"),
    ("PROPERTY_PHYSICAL", "LAND_AREA", "Land area.", "DECIMAL", "12,4", "C",
     "Required for PLOT/LAND/AGRICULTURAL.", "", "2400.0000", "MEDIUM", "",
     "02_field_specification.csv", "N"),
    ("PROPERTY_PHYSICAL", "AREA_UNIT", "Area unit.", "ENUM", "10", "C",
     "Required if area populated.", "AREA_UNIT", "SQFT", "LOW", "",
     "03_enum_master.csv", "N"),
    ("PROPERTY_PHYSICAL", "YEAR_OF_CONSTRUCTION", "Year built.", "INTEGER", "4", "N",
     "1900 to reporting year + 5; UNKNOWN allowed as 0 with warning.", "", "2019", "LOW", "",
     "Critical Evaluation §8.1", "N"),
    ("PROPERTY_PHYSICAL", "NUMBER_OF_FLOORS", "Floors in building.", "INTEGER", "3", "N", "1-200.", "", "18", "LOW", "",
     "02_field_specification.csv", "N"),

    ("TITLE_REGISTRATION", "TITLE_DOCUMENT_TYPE", "Primary title document type.", "ENUM", "30", "N",
     "TITLE_DOCUMENT_TYPE enum.", "TITLE_DOCUMENT_TYPE", "SALE_DEED", "MEDIUM", "",
     "Critical Evaluation §4 consolidation", "N"),
    ("TITLE_REGISTRATION", "TITLE_DOCUMENT_NUMBER", "Title / registration reference.", "STRING", "60", "N",
     "Replaces SALE_DEED_NUMBER + REGISTRATION_NUMBER per FB-011.", "", "REG/2021/123456", "CRITICAL", "",
     "Critical Evaluation §4", "N"),
    ("TITLE_REGISTRATION", "TITLE_DOCUMENT_DATE", "Title document date.", "DATE", "10", "C",
     "Required if TITLE_DOCUMENT_NUMBER populated.", "", "2021-08-15", "HIGH", "",
     "Critical Evaluation §4", "N"),

    ("OWNERSHIP", "OWNER_SEQUENCE", "Owner sequence.", "INTEGER", "2", "Y",
     "1..10 per property.", "", "1", "HIGH", "",
     "02_field_specification.csv", "N"),
    ("OWNERSHIP", "OWNER_NAME", "Legal owner name.", "STRING", "150", "Y", "Min 3 chars.", "", "Rajesh Kumar Sharma", "CRITICAL", "",
     "02_field_specification.csv", "N"),
    ("OWNERSHIP", "OWNER_PAN", "Owner PAN.", "STRING", "10", "N",
     "PAN format + checksum warning.", "", "ABCDE1234F", "CRITICAL", "",
     "VR-008/009 enhanced", "N"),
    ("OWNERSHIP", "OWNER_TYPE", "Owner entity type.", "ENUM", "20", "Y",
     "ENTITY_TYPE enum (renamed per FB-013).", "ENTITY_TYPE", "INDIVIDUAL", "HIGH", "",
     "Critical Evaluation §6.3", "N"),
    ("OWNERSHIP", "OWNERSHIP_PERCENT", "Ownership %.", "DECIMAL", "5,2", "Y",
     "Sum 100 ±1.00; DEFAULT_EQUAL keyword allowed per FB-031.", "", "100.00", "HIGH", "",
     "VR-006 widened", "N"),
    ("OWNERSHIP", "OWNERSHIP_ROLE", "Owner role.", "ENUM", "20", "Y",
     "At least one PRIMARY_OWNER per property VR-NEW-02.", "OWNERSHIP_ROLE", "PRIMARY_OWNER", "MEDIUM", "",
     "Critical Evaluation §5", "N"),

    ("BORROWER", "BORROWER_TYPE", "Borrower constitution.", "ENUM", "20", "Y", "ENTITY_TYPE enum.", "ENTITY_TYPE", "INDIVIDUAL", "HIGH", "",
     "FB-013 rename", "N"),
    ("BORROWER", "BORROWER_NAME", "Borrower name.", "STRING", "150", "Y", "", "", "Rajesh Kumar Sharma", "CRITICAL", "",
     "02_field_specification.csv", "N"),
    ("BORROWER", "BORROWER_PAN", "Borrower PAN.", "STRING", "10", "C",
     "Required for INDIVIDUAL.", "", "ABCDE1234F", "CRITICAL", "",
     "02_field_specification.csv", "N"),
    ("BORROWER", "BORROWER_DATE_OF_BIRTH", "DOB.", "DATE", "10", "C",
     "Required for INDIVIDUAL.", "", "1985-06-12", "MEDIUM", "",
     "02_field_specification.csv", "N"),
    ("BORROWER", "BORROWER_MOBILE", "Mobile.", "STRING", "10", "N", "Regex ^[6-9][0-9]{9}$", "", "9876543210", "LOW", "",
     "02_field_specification.csv", "N"),
    ("BORROWER", "BORROWER_EMAIL", "Email.", "STRING", "120", "N", "", "", "rajesh@example.in", "LOW", "",
     "02_field_specification.csv", "N"),

    ("BORROWER_ADDRESS", "BORROWER_ADDRESS_SAME_AS_PROPERTY", "Borrower address same as collateral.", "ENUM", "1", "N",
     "YES_NO; if Y, skip address fields.", "YES_NO", "Y", "", "FB-014 simplified address.",
     "Critical Evaluation §4", "N"),
    ("BORROWER_ADDRESS", "BORROWER_ADDRESS_LINE_1", "Borrower address line 1.", "STRING", "200", "C",
     "Required if INDIVIDUAL and SAME_AS_PROPERTY=N.", "", "42 Ring Road", "HIGH", "",
     "Critical Evaluation §6.1", "N"),
    ("BORROWER_ADDRESS", "BORROWER_LOCALITY", "Borrower locality.", "STRING", "120", "C", "", "", "Vashi", "HIGH", "", "Critical Evaluation", "N"),
    ("BORROWER_ADDRESS", "BORROWER_CITY", "Borrower city.", "STRING", "80", "C", "", "", "Navi Mumbai", "HIGH", "", "Critical Evaluation", "N"),
    ("BORROWER_ADDRESS", "BORROWER_STATE", "Borrower state.", "ENUM", "3", "C", "INDIAN_STATE_UT.", "INDIAN_STATE_UT", "MH", "HIGH", "", "Critical Evaluation", "N"),
    ("BORROWER_ADDRESS", "BORROWER_PINCODE", "Borrower PIN.", "STRING", "6", "C", "VR-007.", "", "400703", "HIGH", "", "Critical Evaluation", "N"),

    ("CO_BORROWER", "CO_BORROWER_SEQUENCE", "Co-borrower sequence.", "INTEGER", "2", "N",
     "Presence implies co-borrower; CO_BORROWER_FLAG removed FB-010.", "", "1", "MEDIUM", "",
     "Critical Evaluation §2 P2", "N"),
    ("CO_BORROWER", "CO_BORROWER_NAME", "Co-borrower name.", "STRING", "150", "C",
     "Required when sequence populated.", "", "Priya Sharma", "HIGH", "",
     "02_field_specification.csv", "N"),
    ("CO_BORROWER", "CO_BORROWER_PAN", "Co-borrower PAN.", "STRING", "10", "N", "", "", "FGHIJ5678K", "HIGH", "",
     "02_field_specification.csv", "N"),
    ("CO_BORROWER", "CO_BORROWER_RELATIONSHIP", "Relationship.", "ENUM", "30", "N", "RELATIONSHIP_TYPE.", "RELATIONSHIP_TYPE", "SPOUSE", "LOW", "",
     "03_enum_master.csv", "N"),

    ("LOAN_ACCOUNT", "PRODUCT_TYPE", "Loan product.", "ENUM", "30", "Y", "LOAN_PRODUCT_TYPE.", "LOAN_PRODUCT_TYPE", "HOME_LOAN", "LOW", "",
     "03_enum_master.csv", "N"),
    ("LOAN_ACCOUNT", "SANCTION_DATE", "Sanction date.", "DATE", "10", "Y", "ISO 8601.", "", "2022-01-10", "LOW", "",
     "02_field_specification.csv", "N"),
    ("LOAN_ACCOUNT", "DISBURSEMENT_DATE", "Disbursement date.", "DATE", "10", "N", ">= SANCTION_DATE.", "", "2022-02-15", "LOW", "",
     "02_field_specification.csv", "N"),
    ("LOAN_ACCOUNT", "SANCTION_AMOUNT", "Sanctioned amount INR.", "DECIMAL", "18,2", "Y", "Positive.", "", "8500000.00", "LOW", "",
     "02_field_specification.csv", "N"),
    ("LOAN_ACCOUNT", "CURRENT_OUTSTANDING", "Outstanding INR.", "DECIMAL", "18,2", "Y",
     "0 if CLOSED; TOP_UP allows up to 150% sanction.", "", "7234500.00", "LOW", "",
     "VR-012 + TOP_UP FB-021", "N"),
    ("LOAN_ACCOUNT", "INTEREST_RATE", "Annual rate %.", "DECIMAL", "6,4", "N",
     "Used by bureau to derive EMI.", "", "8.7500", "LOW", "EMI derived at bureau FB-016.",
     "Critical Evaluation", "Y"),
    ("LOAN_ACCOUNT", "ACCOUNT_STATUS", "Loan status.", "ENUM", "20", "Y", "ACCOUNT_STATUS.", "ACCOUNT_STATUS", "ACTIVE", "LOW", "",
     "03_enum_master.csv", "N"),
    ("LOAN_ACCOUNT", "ACCOUNT_STATUS_DATE", "Status effective date.", "DATE", "10", "Y", "", "", "2026-03-31", "LOW", "",
     "02_field_specification.csv", "N"),
    ("LOAN_ACCOUNT", "TENURE_MONTHS", "Tenure months.", "INTEGER", "4", "N", "1-600.", "", "240", "LOW", "",
     "02_field_specification.csv", "N"),
    ("LOAN_ACCOUNT", "DPD", "Days past due.", "INTEGER", "5", "N",
     "Bureau derives NPA from DPD per FB-014.", "", "0", "LOW", "",
     "Critical Evaluation §4", "N"),
    ("LOAN_ACCOUNT", "TOP_UP", "Top-up loan indicator.", "ENUM", "1", "N",
     "YES_NO; allows outstanding > sanction per VR-012.", "YES_NO", "N", "LOW", "New FB-021.",
     "Critical Evaluation §5", "N"),

    ("MORTGAGE_CHARGE", "CHARGE_SEQUENCE", "Charge sequence.", "INTEGER", "2", "Y", "", "", "1", "LOW", "",
     "02_field_specification.csv", "N"),
    ("MORTGAGE_CHARGE", "CHARGE_TYPE", "Charge type.", "ENUM", "30", "Y", "CHARGE_TYPE.", "CHARGE_TYPE", "REGISTERED_MORTGAGE", "MEDIUM", "",
     "03_enum_master.csv", "N"),
    ("MORTGAGE_CHARGE", "CHARGE_AMOUNT", "Secured amount.", "DECIMAL", "18,2", "C",
     "Defaults to SANCTION_AMOUNT if blank FB-017.", "", "8500000.00", "LOW", "",
     "Critical Evaluation §2 P3", "Y"),
    ("MORTGAGE_CHARGE", "CHARGE_REGISTRATION_DATE", "Charge registration date.", "DATE", "10", "C",
     "Required for REGISTERED_MORTGAGE.", "", "2022-03-01", "MEDIUM", "",
     "02_field_specification.csv", "N"),
    ("MORTGAGE_CHARGE", "CHARGE_REGISTRATION_NUMBER", "Charge registration ref.", "STRING", "60", "C",
     "Required for REGISTERED_MORTGAGE.", "", "CHG/2022/99881", "HIGH", "",
     "02_field_specification.csv", "N"),
    ("MORTGAGE_CHARGE", "CHARGE_STATUS", "Charge status.", "ENUM", "20", "Y", "CHARGE_STATUS.", "CHARGE_STATUS", "ACTIVE", "LOW", "",
     "03_enum_master.csv + PENDING_REGISTRATION", "N"),
    ("MORTGAGE_CHARGE", "CHARGE_RELEASE_DATE", "Release date.", "DATE", "10", "C",
     "Required if RELEASED.", "", "", "LOW", "",
     "VR-017", "N"),
    ("MORTGAGE_CHARGE", "PRIOR_CHARGE_HOLDER_NAME", "Prior charge holder.", "STRING", "150", "N",
     "Non-null implies prior charge; flag removed FB-023.", "", "", "MEDIUM", "",
     "Critical Evaluation §2 P4", "N"),

    ("VALUATION", "VALUATION_SEQUENCE", "Valuation sequence.", "INTEGER", "2", "N", "", "", "1", "LOW", "",
     "02_field_specification.csv", "N"),
    ("VALUATION", "VALUATION_DATE", "Valuation date.", "DATE", "10", "C",
     "Required if amount populated; latest = max date FB-015.", "", "2025-11-20", "LOW", "",
     "Critical Evaluation", "N"),
    ("VALUATION", "VALUATION_AMOUNT", "Value INR.", "DECIMAL", "18,2", "N", "", "", "12500000.00", "LOW", "",
     "02_field_specification.csv", "N"),
    ("VALUATION", "VALUATION_TYPE", "Valuation basis.", "ENUM", "20", "N", "VALUATION_TYPE.", "VALUATION_TYPE", "MARKET_VALUE", "LOW", "",
     "03_enum_master.csv", "N"),
    ("VALUATION", "VALUATOR_NAME", "Valuer name.", "STRING", "150", "N", "", "", "Knight Frank India", "LOW", "",
     "02_field_specification.csv", "N"),

    ("DOCUMENT_STATUS", "TITLE_DEED_AVAILABILITY", "Title deed custody.", "ENUM", "20", "N", "DOCUMENT_AVAILABILITY.", "DOCUMENT_AVAILABILITY", "AVAILABLE", "LOW", "",
     "03_enum_master.csv + SURRENDERED", "N"),
    ("DOCUMENT_STATUS", "SALE_DEED_AVAILABILITY", "Sale deed availability.", "ENUM", "20", "N", "DOCUMENT_AVAILABILITY.", "DOCUMENT_AVAILABILITY", "AVAILABLE", "LOW", "",
     "02_field_specification.csv", "N"),
    ("DOCUMENT_STATUS", "ENCUMBRANCE_CERTIFICATE_AVAILABILITY", "EC availability.", "ENUM", "20", "N", "DOCUMENT_AVAILABILITY.", "DOCUMENT_AVAILABILITY", "PENDING", "LOW", "",
     "02_field_specification.csv", "N"),
    ("DOCUMENT_STATUS", "OCCUPANCY_CERTIFICATE_AVAILABILITY", "OC availability.", "ENUM", "20", "N", "DOCUMENT_AVAILABILITY.", "DOCUMENT_AVAILABILITY", "NOT_APPLICABLE", "LOW", "",
     "02_field_specification.csv", "N"),
    ("DOCUMENT_STATUS", "APPROVED_PLAN_AVAILABILITY", "Plan approval.", "ENUM", "20", "N", "DOCUMENT_AVAILABILITY.", "DOCUMENT_AVAILABILITY", "AVAILABLE", "LOW", "",
     "02_field_specification.csv", "N"),

    ("GEOCODE_OPTIONAL", "LATITUDE", "WGS84 latitude.", "DECIMAL", "12,8", "N", "", "", "12.91230000", "MEDIUM", "Optional enrichment.",
     "02_field_specification.csv", "N"),
    ("GEOCODE_OPTIONAL", "LONGITUDE", "WGS84 longitude.", "DECIMAL", "12,8", "N", "", "", "77.64450000", "MEDIUM", "",
     "02_field_specification.csv", "N"),

    ("EXTENDED_OPTIONAL", "BRANCH_CODE", "Member branch code.", "STRING", "20", "N",
     "No bureau validation; enrichment only FB-022.", "", "BR-MUM-014", "", "",
     "Critical Evaluation P4", "N"),
    ("EXTENDED_OPTIONAL", "REGION_CODE", "Member region code.", "STRING", "20", "N", "", "", "WEST-02", "", "",
     "Critical Evaluation P4", "N"),
    ("EXTENDED_OPTIONAL", "PROPERTY_DESCRIPTION", "Free-text description.", "STRING", "500", "N",
     "Enrichment only; removed from mandatory FB-011.", "", "3 BHK apartment", "MEDIUM", "",
     "Critical Evaluation P2", "N"),
    ("EXTENDED_OPTIONAL", "ADDRESS_LINE_2", "Secondary address.", "STRING", "200", "N", "", "", "Near Metro", "HIGH", "",
     "02_field_specification.csv", "N"),
    ("EXTENDED_OPTIONAL", "LANDMARK", "Landmark.", "STRING", "120", "N", "", "", "Opposite station", "MEDIUM", "",
     "02_field_specification.csv", "N"),
]

REMOVED_FIELDS_V10 = [
    ("SUBMISSION_DATE", "FB-005", "Bureau ingestion timestamp"),
    ("DATA_AS_OF_DATE", "FB-004", "Defaults to REPORTING_PERIOD_END"),
    ("DELIMITER", "FB-006", "API/HTTP metadata"),
    ("ENCODING", "FB-006", "System UTF-8"),
    ("FILE_VERSION", "FB-006", "Standard version in manifest"),
    ("MEMBER_INSTITUTION_NAME", "FB-007", "Derived from MEMBER_INSTITUTION_CODE"),
    ("COUNTRY", "FB-008", "System default IN"),
    ("BORROWER_COUNTRY", "FB-008", "System default IN"),
    ("PROPERTY_AGE_YEARS", "FB-003", "REPORTING_YEAR - YEAR_OF_CONSTRUCTION"),
    ("CO_BORROWER_FLAG", "FB-010", "Inferred from CO_BORROWER rows"),
    ("NPA_CLASSIFICATION", "FB-014", "Derived from DPD"),
    ("IS_LATEST_VALUATION", "FB-015", "max(VALUATION_DATE)"),
    ("EMI_AMOUNT", "FB-016", "Derived from sanction/rate/tenure"),
    ("PRIOR_CHARGE_EXISTS", "FB-023", "Inferred from PRIOR_CHARGE_HOLDER_NAME"),
    ("LAST_DOCUMENT_REVIEW_DATE", "FB-013", "Operational only"),
    ("REGISTRAR_OFFICE", "FB-010", "Low value free text"),
    ("BUILDING_NAME", "FB-009", "Merged to BUILDING_UNIT_IDENTIFIER"),
    ("TOWER_NAME", "FB-009", "Merged to BUILDING_UNIT_IDENTIFIER"),
    ("SALE_DEED_NUMBER", "FB-011", "Merged to TITLE_DOCUMENT_NUMBER"),
    ("REGISTRATION_NUMBER", "FB-011", "Merged to TITLE_DOCUMENT_NUMBER"),
    ("REGISTRATION_DATE", "FB-011", "Merged to TITLE_DOCUMENT_DATE"),
    ("KHATA_NUMBER", "FB-012", "Merged to MUNICIPAL_AUTHORITY_ID"),
    ("MUNICIPAL_PROPERTY_ID", "FB-012", "Merged to MUNICIPAL_AUTHORITY_ID"),
    ("PROPERTY_TAX_NUMBER", "FB-012", "Merged to MUNICIPAL_AUTHORITY_ID"),
    ("BORROWER_ADDRESS_LINE_2", "FB-014", "Dropped from core borrower address"),
    ("BORROWER_LANDMARK", "FB-014", "Dropped"),
    ("BORROWER_DISTRICT", "FB-014", "Derived from PINCODE"),
    ("BORROWER_ADDRESS_TYPE", "FB-014", "Deferred to V2"),
]

ENUMS_V11 = [
    ("SUBMISSION_TYPE", "FULL", "Full refresh", "1"),
    ("SUBMISSION_TYPE", "DELTA", "Incremental", "2"),
    ("SUBMISSION_TYPE", "REFRESH", "Correction resubmit", "3"),
    ("RECORD_TYPE", "FILE_HEADER", "Batch header (legacy combined file)", "1"),
    ("RECORD_TYPE", "PROPERTY", "Property collateral", "2"),
    ("RECORD_TYPE", "OWNERSHIP", "Ownership", "3"),
    ("RECORD_TYPE", "BORROWER", "Borrower", "4"),
    ("RECORD_TYPE", "CO_BORROWER", "Co-borrower", "5"),
    ("RECORD_TYPE", "LOAN_ACCOUNT", "Loan", "6"),
    ("RECORD_TYPE", "MORTGAGE_CHARGE", "Charge", "7"),
    ("RECORD_TYPE", "VALUATION", "Valuation", "8"),
    ("RECORD_TYPE", "DOCUMENT_STATUS", "Documents", "9"),
    ("PROPERTY_TYPE", "RESIDENTIAL", "Residential", "1"),
    ("PROPERTY_TYPE", "COMMERCIAL", "Commercial", "2"),
    ("PROPERTY_TYPE", "INDUSTRIAL", "Industrial", "3"),
    ("PROPERTY_TYPE", "AGRICULTURAL", "Agricultural", "4"),
    ("PROPERTY_TYPE", "MIXED_USE", "Mixed use", "5"),
    ("PROPERTY_SUBTYPE", "APARTMENT", "Apartment", "1"),
    ("PROPERTY_SUBTYPE", "VILLA", "Villa", "2"),
    ("PROPERTY_SUBTYPE", "ROW_HOUSE", "Row house", "3"),
    ("PROPERTY_SUBTYPE", "PLOT", "Plot", "4"),
    ("PROPERTY_SUBTYPE", "OFFICE", "Office", "5"),
    ("PROPERTY_SUBTYPE", "SHOP", "Shop", "6"),
    ("PROPERTY_SUBTYPE", "WAREHOUSE", "Warehouse", "7"),
    ("PROPERTY_SUBTYPE", "FACTORY", "Factory", "8"),
    ("PROPERTY_SUBTYPE", "LAND", "Land", "9"),
    ("ENTITY_TYPE", "INDIVIDUAL", "Individual", "1"),
    ("ENTITY_TYPE", "PROPRIETORSHIP", "Proprietorship", "2"),
    ("ENTITY_TYPE", "PARTNERSHIP", "Partnership", "3"),
    ("ENTITY_TYPE", "PRIVATE_LIMITED", "Private limited", "4"),
    ("ENTITY_TYPE", "PUBLIC_LIMITED", "Public limited", "5"),
    ("ENTITY_TYPE", "LLP", "LLP", "6"),
    ("ENTITY_TYPE", "TRUST", "Trust", "7"),
    ("ENTITY_TYPE", "SOCIETY", "Society", "8"),
    ("ACCOUNT_STATUS", "ACTIVE", "Active", "1"),
    ("ACCOUNT_STATUS", "CLOSED", "Closed", "2"),
    ("ACCOUNT_STATUS", "SETTLED", "Settled", "3"),
    ("ACCOUNT_STATUS", "WRITTEN_OFF", "Written off", "4"),
    ("ACCOUNT_STATUS", "RESTRUCTURED", "Restructured", "5"),
    ("CHARGE_TYPE", "FIRST_CHARGE", "First charge", "1"),
    ("CHARGE_TYPE", "SECOND_CHARGE", "Second charge", "2"),
    ("CHARGE_TYPE", "PARI_PASSU", "Pari passu", "3"),
    ("CHARGE_TYPE", "EQUITABLE_MORTGAGE", "Equitable mortgage", "4"),
    ("CHARGE_TYPE", "REGISTERED_MORTGAGE", "Registered mortgage", "5"),
    ("CHARGE_STATUS", "ACTIVE", "Active", "1"),
    ("CHARGE_STATUS", "RELEASED", "Released", "2"),
    ("CHARGE_STATUS", "PARTIALLY_RELEASED", "Partial", "3"),
    ("CHARGE_STATUS", "PENDING_REGISTRATION", "Pending registration", "4"),
    ("AREA_UNIT", "SQFT", "Square feet", "1"),
    ("AREA_UNIT", "SQM", "Square metres", "2"),
    ("AREA_UNIT", "ACRE", "Acre", "3"),
    ("AREA_UNIT", "HECTARE", "Hectare", "4"),
    ("AREA_UNIT", "GUNTHA", "Guntha", "5"),
    ("AREA_UNIT", "BIGHA", "Bigha", "6"),
    ("DOCUMENT_AVAILABILITY", "AVAILABLE", "Available", "1"),
    ("DOCUMENT_AVAILABILITY", "NOT_AVAILABLE", "Not available", "2"),
    ("DOCUMENT_AVAILABILITY", "PENDING", "Pending", "3"),
    ("DOCUMENT_AVAILABILITY", "NOT_APPLICABLE", "N/A", "4"),
    ("DOCUMENT_AVAILABILITY", "SURRENDERED", "Surrendered to institution", "5"),
    ("OCCUPANCY_STATUS", "SELF_OCCUPIED", "Self occupied", "1"),
    ("OCCUPANCY_STATUS", "RENTED", "Rented", "2"),
    ("OCCUPANCY_STATUS", "VACANT", "Vacant", "3"),
    ("CONSTRUCTION_STATUS", "COMPLETED", "Completed", "3"),
    ("CONSTRUCTION_STATUS", "UNDER_CONSTRUCTION", "Under construction", "2"),
    ("CONSTRUCTION_STATUS", "PLOT_ONLY", "Plot only", "1"),
    ("MUNICIPAL_ID_TYPE", "KHATA", "Khata", "1"),
    ("MUNICIPAL_ID_TYPE", "PID", "Municipal property ID", "2"),
    ("MUNICIPAL_ID_TYPE", "PTIN", "Property tax ID", "3"),
    ("MUNICIPAL_ID_TYPE", "OTHER", "Other ULB id", "4"),
    ("YES_NO", "Y", "Yes", "1"),
    ("YES_NO", "N", "No", "2"),
    ("LOAN_PRODUCT_TYPE", "HOME_LOAN", "Home loan", "1"),
    ("LOAN_PRODUCT_TYPE", "LAP", "LAP", "2"),
    ("LOAN_PRODUCT_TYPE", "CONSTRUCTION_LOAN", "Construction", "3"),
    ("LOAN_PRODUCT_TYPE", "COMMERCIAL_PROPERTY_LOAN", "Commercial property", "4"),
    ("LOAN_PRODUCT_TYPE", "PLOT_LOAN", "Plot loan", "5"),
    ("VALUATION_TYPE", "MARKET_VALUE", "Market", "1"),
    ("VALUATION_TYPE", "DISTRESS_VALUE", "Distress", "2"),
    ("VALUATION_TYPE", "BOOK_VALUE", "Book", "3"),
    ("VALUATION_TYPE", "FAIR_VALUE", "Fair", "4"),
    ("OWNERSHIP_ROLE", "PRIMARY_OWNER", "Primary", "1"),
    ("OWNERSHIP_ROLE", "CO_OWNER", "Co-owner", "2"),
    ("OWNERSHIP_ROLE", "GUARANTOR", "Guarantor", "3"),
    ("TITLE_DOCUMENT_TYPE", "SALE_DEED", "Sale deed", "1"),
    ("TITLE_DOCUMENT_TYPE", "GIFT_DEED", "Gift deed", "2"),
    ("TITLE_DOCUMENT_TYPE", "LEASE_DEED", "Lease", "3"),
    ("TITLE_DOCUMENT_TYPE", "ALLOTMENT_LETTER", "Allotment", "4"),
    ("TITLE_DOCUMENT_TYPE", "AGREEMENT_TO_SELL", "ATS", "5"),
    ("RELATIONSHIP_TYPE", "SPOUSE", "Spouse", "1"),
    ("RELATIONSHIP_TYPE", "PARENT", "Parent", "2"),
    ("RELATIONSHIP_TYPE", "CHILD", "Child", "3"),
    ("RELATIONSHIP_TYPE", "SIBLING", "Sibling", "4"),
    ("RELATIONSHIP_TYPE", "BUSINESS_PARTNER", "Partner", "5"),
    ("RELATIONSHIP_TYPE", "OTHER", "Other", "6"),
]

# Indian states - abbreviated list; full set loaded from v1 csv in builder
INDIAN_STATES = [
    ("INDIAN_STATE_UT", "MH", "Maharashtra"), ("INDIAN_STATE_UT", "KA", "Karnataka"),
    ("INDIAN_STATE_UT", "DL", "Delhi"), ("INDIAN_STATE_UT", "TN", "Tamil Nadu"),
    ("INDIAN_STATE_UT", "GJ", "Gujarat"), ("INDIAN_STATE_UT", "UP", "Uttar Pradesh"),
    ("INDIAN_STATE_UT", "WB", "West Bengal"), ("INDIAN_STATE_UT", "RJ", "Rajasthan"),
    ("INDIAN_STATE_UT", "TS", "Telangana"), ("INDIAN_STATE_UT", "HR", "Haryana"),
]

VALIDATIONS_V11 = [
    ("VR-001", "SUBMISSION_REFERENCE", "ERROR", "Duplicate batch reference within 24 months.", "Duplicate submission reference.", "Use REFRESH or new reference."),
    ("VR-002", "TOTAL_RECORD_COUNT", "INFO", "Bureau counts rows; mismatch reported in ACK.", "Record count differs from header.", "Optional field; fix count or omit."),
    ("VR-006", "OWNERSHIP_PERCENT", "ERROR", "Sum must be 99.00-101.00 per property.", "Ownership sum out of range.", "Adjust shares or use DEFAULT_EQUAL."),
    ("VR-006B", "OWNERSHIP_PERCENT", "WARNING", "Sum 98.00-102.00 triggers review.", "Ownership rounding warning.", ""),
    ("VR-007", "PINCODE", "ERROR", "Valid 6-digit PIN; bureau PIN master check.", "Invalid PIN.", "400703"),
    ("VR-007B", "BORROWER_PINCODE", "ERROR", "Same as VR-007.", "Invalid borrower PIN.", ""),
    ("VR-008", "BORROWER_PAN", "ERROR", "PAN format uppercase.", "Invalid PAN format.", "ABCDE1234F"),
    ("VR-008B", "BORROWER_PAN", "WARNING", "PAN checksum digit validation.", "PAN checksum mismatch.", ""),
    ("VR-009", "OWNER_PAN", "ERROR", "Same as VR-008 when populated.", "Invalid owner PAN.", ""),
    ("VR-010", "BORROWER_MOBILE", "ERROR", "Mobile ^[6-9][0-9]{9}$.", "Invalid mobile.", ""),
    ("VR-011", "SANCTION_AMOUNT", "ERROR", "DECIMAL(18,2) no symbols.", "Invalid amount.", ""),
    ("VR-012", "CURRENT_OUTSTANDING", "ERROR", "0 if CLOSED; <=150% sanction if TOP_UP=Y else <= sanction.", "Outstanding invalid.", ""),
    ("VR-014", "SURVEY_NUMBER", "ERROR", "Required for AGRICULTURAL or PLOT/LAND.", "Survey required.", ""),
    ("VR-015", "FLAT_NUMBER", "ERROR", "Required for APARTMENT/OFFICE/SHOP.", "Flat number required.", ""),
    ("VR-017", "CHARGE_RELEASE_DATE", "ERROR", "Required if RELEASED; >= registration date.", "Invalid release date.", ""),
    ("VR-018", "REPORTING_PERIOD_END", "ERROR", "ISO date YYYY-MM-DD.", "Invalid date format.", "2026-03-31"),
    ("VR-019", "PROPERTY_SUBTYPE", "ERROR", "Must match PROPERTY_TYPE crosswalk.", "Invalid subtype.", ""),
    ("VR-020", "MEMBER_PROPERTY_REFERENCE", "WARNING", "Matching score >= 60/100 required.", "Low matching score.", "See matching score table."),
    ("VR-NEW-01", "YEAR_OF_CONSTRUCTION", "ERROR", "If COMPLETED, year <= reporting year.", "Future construction year.", ""),
    ("VR-NEW-02", "OWNERSHIP_ROLE", "ERROR", "At least one PRIMARY_OWNER per property.", "No primary owner.", ""),
    ("VR-NEW-03", "CHARGE_AMOUNT", "WARNING", "CHARGE_AMOUNT > 1.5x SANCTION_AMOUNT.", "Charge amount anomaly.", ""),
    ("VR-BA-001", "BORROWER_ADDRESS_SAME_AS_PROPERTY", "ERROR", "If Y, property address must exist.", "Same-as-property without collateral address.", ""),
    ("VR-BA-002", "BORROWER_ADDRESS_LINE_1", "ERROR", "Required for INDIVIDUAL when SAME_AS_PROPERTY=N.", "Borrower address required.", ""),
    ("VR-MUNI", "MUNICIPAL_ID_TYPE", "ERROR", "Required when MUNICIPAL_AUTHORITY_ID populated.", "Municipal id type required.", ""),
    ("VR-TITLE", "TITLE_DOCUMENT_DATE", "ERROR", "Required when TITLE_DOCUMENT_NUMBER populated.", "Title date required.", ""),
    ("VR-VAL-01", "VALUATION_DATE", "WARNING", "Duplicate valuation dates for same property.", "Duplicate valuation date.", ""),
]

MATCHING_SCORE = [
    ("PINCODE", 20), ("FLAT_NUMBER", 20), ("PLOT_NUMBER", 20), ("LOCALITY", 15),
    ("PROJECT_NAME", 15), ("OWNER_PAN", 15), ("BORROWER_PAN", 15),
    ("CTS_NUMBER", 15), ("SURVEY_NUMBER", 15), ("TITLE_DOCUMENT_NUMBER", 15),
]

# Option B — primary V1.1 format: one row per loan/collateral package (dense, non-sparse)
DENSE_SINGLE_FILE_NAME = "PROPERTY_BUREAU_SUBMISSION.csv"

DENSE_SINGLE_FILE_LAYOUT = [
    (DENSE_SINGLE_FILE_NAME, "DENSE_SUBMISSION", "1..n", "One row per MEMBER_LOAN_ACCOUNT_NUMBER; all core fields populated on each row"),
    ("OWNERSHIP_SUPPLEMENT.csv", "OWNERSHIP_SUPPLEMENT", "0..9 per property", "Additional owners when >1 owner; link MEMBER_PROPERTY_REFERENCE"),
    ("CO_BORROWER_SUPPLEMENT.csv", "CO_BORROWER_SUPPLEMENT", "0..4 per loan", "Additional co-borrowers when >1; link MEMBER_LOAN_ACCOUNT_NUMBER"),
]

MULTI_FILE_LAYOUT = [
    ("01_SUBMISSION_HEADER.csv", "FILE_HEADER", "1", "Alternate: multi-file package for core-banking batch exports"),
    ("02_PROPERTY.csv", "PROPERTY", "1..n", "MEMBER_PROPERTY_REFERENCE + property sections"),
    ("03_OWNERSHIP.csv", "OWNERSHIP", "1..10 per property", "MEMBER_PROPERTY_REFERENCE + OWNERSHIP fields"),
    ("04_BORROWER.csv", "BORROWER", "1 per loan", "MEMBER_LOAN_ACCOUNT_NUMBER + BORROWER + BORROWER_ADDRESS"),
    ("05_CO_BORROWER.csv", "CO_BORROWER", "0..5", "MEMBER_LOAN_ACCOUNT_NUMBER + CO_BORROWER fields"),
    ("06_LOAN_ACCOUNT.csv", "LOAN_ACCOUNT", "1 per loan", "MEMBER_LOAN_ACCOUNT_NUMBER + LOAN fields"),
    ("07_MORTGAGE_CHARGE.csv", "MORTGAGE_CHARGE", "1..n", "MEMBER_LOAN_ACCOUNT_NUMBER + CHARGE fields"),
    ("08_VALUATION.csv", "VALUATION", "0..n", "MEMBER_PROPERTY_REFERENCE + VALUATION fields"),
    ("09_DOCUMENT_STATUS.csv", "DOCUMENT_STATUS", "0..1 per property", "MEMBER_PROPERTY_REFERENCE + DOCUMENT fields"),
]

LEGACY_LAYOUT = [
    ("LEGACY_RECORD_TYPE_COMBINED.csv", "LEGACY", "Deprecated", "Sparse multi-record single file with RECORD_TYPE column — do not use for new integrations"),
]


def dense_submission_column_order() -> list[str]:
    """Column order for Option B dense single-file submission."""
    priority = [
        "SUBMISSION_REFERENCE", "MEMBER_INSTITUTION_CODE", "REPORTING_PERIOD_END", "SUBMISSION_TYPE",
        "CONTACT_EMAIL", "TOTAL_RECORD_COUNT",
        "MEMBER_LOAN_ACCOUNT_NUMBER", "MEMBER_PROPERTY_REFERENCE", "MEMBER_CUSTOMER_ID",
    ]
    skip = {"RECORD_TYPE"}
    names = [f[1] for f in FIELDS_V11 if f[1] not in skip]
    ordered = [n for n in priority if n in names]
    ordered += [n for n in names if n not in ordered]
    return ordered
